### ISSUE TITLE
Support video type for VirtualBackground

### ISSUE THREAD

**Issue by devsideal** [AgoraIO-Community/Android-UIKit#33]
**Is your feature request related to a problem? Please describe.**
Can you provide support for video type in VirtualBackground.

**Describe the solution you'd like**
If possible add one more type in VirtualBackgroundSource to give support for the video.

**Describe alternatives you've considered**
Currently looks like, there is no way to show animated background in the video.

https://www.agora.io/en/blog/add-custom-backgrounds-to-your-live-video-calling-application-using-the-agora-android-uikit/

**Comment by maxxfrazer** [comment]
Hi @devsideal, looks like this is more a request for the core SDK, rather than the Video UI Kit. We can't add this feature as it's not currently in the core SDK. I agree that it would be a great addition!

Best bet is to add a ticket in https://agora-ticket.agora.io (if you're in the Agora console, click Support at the top). Let us know the ticket # here so we can follow up internally.
Creating a ticket helps us show there's demand for a given feature for the SDK team to build out.

**Comment by devsideal** [comment]
Hi @maxxfrazer, Thanks for the suggestion.
I have created a ticket #CUS-29078 on the agora console.
